// TYPES for AUTH_ACTIONS
export const GET_LOGIN_AUTH = "GET_LOGIN_AUTH"
export const TOGGLE_USER_LOADING = 'TOGGLE_USER_LOADING'
export const TOGGLE_USER_IS_AUTH = 'TOGGLE_USER_IS_AUTH'
export const GET_USER_DATA = 'GET_USER_DATA'
export const LOGOUT = 'LOGOUT'
export const VERIFY = 'VERIFY'
export const REGISTER_USER = "REGISTER_USER"
export const CHECK_IS_AUTH = 'CHECK_IS_AUTH'

// TYPES for EXER_ACTIONS

export const ADD_NEW_EXER = "ADD_NEW_EXER"
export const DELETE_EXER = "DELETE_EXER"
export const UPDATE_EXERCISES = "UPDATE_EXERCISES"
export const CHANGE_ORDER_EXERCISES = "CHANGE_ORDER_EXERCISES"

// TYPES for WORKOUT_ACTIONS

export const ADD_NEW_WORKOUT = "ADD_NEW_WORKOUT"
export const UPDATE_WORKOUT = "UPDATE_WORKOUT"

// TYPES for DASHBOARD_ACTION
 export const SET_DATE = "SET_DATE"